// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum GalleryPermission {
  /// Full access to images.
  granted,

  /// Android 14+ partial access to images the user picked.
  partial,
  denied,

  /// Denied and Android will no longer show the prompt.
  permanentlyDenied,
}

class GalleryImage {
  GalleryImage({
    required this.uri,
    required this.takenAtMillis,
    required this.width,
    required this.height,
    required this.byteSize,
    required this.mimeType,
  });

  /// `content://` URI.
  String uri;

  int takenAtMillis;

  int width;

  int height;

  int byteSize;

  String mimeType;

  List<Object?> _toList() {
    return <Object?>[uri, takenAtMillis, width, height, byteSize, mimeType];
  }

  Object encode() {
    return _toList();
  }

  static GalleryImage decode(Object result) {
    result as List<Object?>;
    return GalleryImage(
      uri: result[0]! as String,
      takenAtMillis: result[1]! as int,
      width: result[2]! as int,
      height: result[3]! as int,
      byteSize: result[4]! as int,
      mimeType: result[5]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GalleryImage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uri, other.uri) &&
        _deepEquals(takenAtMillis, other.takenAtMillis) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(byteSize, other.byteSize) &&
        _deepEquals(mimeType, other.mimeType);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GalleryImage(uri: $uri, takenAtMillis: $takenAtMillis, width: $width, height: $height, byteSize: $byteSize, mimeType: $mimeType)';
  }
}

class GalleryPage {
  GalleryPage({required this.images, required this.hasMore});

  List<GalleryImage> images;

  bool hasMore;

  List<Object?> _toList() {
    return <Object?>[images, hasMore];
  }

  Object encode() {
    return _toList();
  }

  static GalleryPage decode(Object result) {
    result as List<Object?>;
    return GalleryPage(
      images: (result[0]! as List<Object?>).cast<GalleryImage>(),
      hasMore: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GalleryPage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(images, other.images) &&
        _deepEquals(hasMore, other.hasMore);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GalleryPage(images: $images, hasMore: $hasMore)';
  }
}

/// A file copied into app storage.
class CopiedImage {
  CopiedImage({
    required this.sourceUri,
    required this.relativePath,
    required this.sha256,
    required this.mimeType,
    required this.width,
    required this.height,
    required this.byteSize,
    required this.takenAtMillis,
  });

  String sourceUri;

  /// Relative to the app files dir, for example `originals/<uuid>.png`.
  String relativePath;

  String sha256;

  String mimeType;

  int width;

  int height;

  int byteSize;

  int takenAtMillis;

  List<Object?> _toList() {
    return <Object?>[
      sourceUri,
      relativePath,
      sha256,
      mimeType,
      width,
      height,
      byteSize,
      takenAtMillis,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CopiedImage decode(Object result) {
    result as List<Object?>;
    return CopiedImage(
      sourceUri: result[0]! as String,
      relativePath: result[1]! as String,
      sha256: result[2]! as String,
      mimeType: result[3]! as String,
      width: result[4]! as int,
      height: result[5]! as int,
      byteSize: result[6]! as int,
      takenAtMillis: result[7]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CopiedImage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sourceUri, other.sourceUri) &&
        _deepEquals(relativePath, other.relativePath) &&
        _deepEquals(sha256, other.sha256) &&
        _deepEquals(mimeType, other.mimeType) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(byteSize, other.byteSize) &&
        _deepEquals(takenAtMillis, other.takenAtMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CopiedImage(sourceUri: $sourceUri, relativePath: $relativePath, sha256: $sha256, mimeType: $mimeType, width: $width, height: $height, byteSize: $byteSize, takenAtMillis: $takenAtMillis)';
  }
}

class CopyFailure {
  CopyFailure({required this.sourceUri, required this.message});

  String sourceUri;

  String message;

  List<Object?> _toList() {
    return <Object?>[sourceUri, message];
  }

  Object encode() {
    return _toList();
  }

  static CopyFailure decode(Object result) {
    result as List<Object?>;
    return CopyFailure(
      sourceUri: result[0]! as String,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CopyFailure || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sourceUri, other.sourceUri) &&
        _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CopyFailure(sourceUri: $sourceUri, message: $message)';
  }
}

class CopyResult {
  CopyResult({required this.copied, required this.failed});

  List<CopiedImage> copied;

  List<CopyFailure> failed;

  List<Object?> _toList() {
    return <Object?>[copied, failed];
  }

  Object encode() {
    return _toList();
  }

  static CopyResult decode(Object result) {
    result as List<Object?>;
    return CopyResult(
      copied: (result[0]! as List<Object?>).cast<CopiedImage>(),
      failed: (result[1]! as List<Object?>).cast<CopyFailure>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CopyResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(copied, other.copied) &&
        _deepEquals(failed, other.failed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CopyResult(copied: $copied, failed: $failed)';
  }
}

class CaptureStatus {
  CaptureStatus({
    required this.accessibilitySupported,
    required this.accessibilityEnabled,
    required this.canRequestTile,
    required this.notificationsAllowed,
  });

  /// Android 11 or newer.
  bool accessibilitySupported;

  bool accessibilityEnabled;

  /// Android 13+ can prompt to add the tile directly.
  bool canRequestTile;

  bool notificationsAllowed;

  List<Object?> _toList() {
    return <Object?>[
      accessibilitySupported,
      accessibilityEnabled,
      canRequestTile,
      notificationsAllowed,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CaptureStatus decode(Object result) {
    result as List<Object?>;
    return CaptureStatus(
      accessibilitySupported: result[0]! as bool,
      accessibilityEnabled: result[1]! as bool,
      canRequestTile: result[2]! as bool,
      notificationsAllowed: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CaptureStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accessibilitySupported, other.accessibilitySupported) &&
        _deepEquals(accessibilityEnabled, other.accessibilityEnabled) &&
        _deepEquals(canRequestTile, other.canRequestTile) &&
        _deepEquals(notificationsAllowed, other.notificationsAllowed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CaptureStatus(accessibilitySupported: $accessibilitySupported, accessibilityEnabled: $accessibilityEnabled, canRequestTile: $canRequestTile, notificationsAllowed: $notificationsAllowed)';
  }
}

/// A capture or share waiting in `files/inbox/`.
class InboxItem {
  InboxItem({
    required this.id,
    required this.relativePath,
    required this.source,
    required this.capturedAtMillis,
    required this.sha256,
    required this.mimeType,
    required this.width,
    required this.height,
    required this.byteSize,
  });

  /// Inbox id, passed back to [CaptureHostApi.confirmInbox] once the memory
  /// row exists.
  String id;

  String relativePath;

  /// `tile` or `share`.
  String source;

  int capturedAtMillis;

  String sha256;

  String mimeType;

  int width;

  int height;

  int byteSize;

  List<Object?> _toList() {
    return <Object?>[
      id,
      relativePath,
      source,
      capturedAtMillis,
      sha256,
      mimeType,
      width,
      height,
      byteSize,
    ];
  }

  Object encode() {
    return _toList();
  }

  static InboxItem decode(Object result) {
    result as List<Object?>;
    return InboxItem(
      id: result[0]! as String,
      relativePath: result[1]! as String,
      source: result[2]! as String,
      capturedAtMillis: result[3]! as int,
      sha256: result[4]! as String,
      mimeType: result[5]! as String,
      width: result[6]! as int,
      height: result[7]! as int,
      byteSize: result[8]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InboxItem || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(relativePath, other.relativePath) &&
        _deepEquals(source, other.source) &&
        _deepEquals(capturedAtMillis, other.capturedAtMillis) &&
        _deepEquals(sha256, other.sha256) &&
        _deepEquals(mimeType, other.mimeType) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(byteSize, other.byteSize);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'InboxItem(id: $id, relativePath: $relativePath, source: $source, capturedAtMillis: $capturedAtMillis, sha256: $sha256, mimeType: $mimeType, width: $width, height: $height, byteSize: $byteSize)';
  }
}

class SchedulePolicy {
  SchedulePolicy({
    required this.immediate,
    required this.paused,
    required this.windowStartMinutes,
    required this.windowEndMinutes,
    required this.requiresUnmeteredNetwork,
    required this.hasWork,
  });

  bool immediate;

  bool paused;

  int windowStartMinutes;

  int windowEndMinutes;

  /// True when a selected capability sends data off the device.
  bool requiresUnmeteredNetwork;

  /// False lets the scheduler cancel pending work.
  bool hasWork;

  List<Object?> _toList() {
    return <Object?>[
      immediate,
      paused,
      windowStartMinutes,
      windowEndMinutes,
      requiresUnmeteredNetwork,
      hasWork,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SchedulePolicy decode(Object result) {
    result as List<Object?>;
    return SchedulePolicy(
      immediate: result[0]! as bool,
      paused: result[1]! as bool,
      windowStartMinutes: result[2]! as int,
      windowEndMinutes: result[3]! as int,
      requiresUnmeteredNetwork: result[4]! as bool,
      hasWork: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SchedulePolicy || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(immediate, other.immediate) &&
        _deepEquals(paused, other.paused) &&
        _deepEquals(windowStartMinutes, other.windowStartMinutes) &&
        _deepEquals(windowEndMinutes, other.windowEndMinutes) &&
        _deepEquals(requiresUnmeteredNetwork, other.requiresUnmeteredNetwork) &&
        _deepEquals(hasWork, other.hasWork);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SchedulePolicy(immediate: $immediate, paused: $paused, windowStartMinutes: $windowStartMinutes, windowEndMinutes: $windowEndMinutes, requiresUnmeteredNetwork: $requiresUnmeteredNetwork, hasWork: $hasWork)';
  }
}

class RunResult {
  RunResult({required this.processed, required this.remaining});

  int processed;

  bool remaining;

  List<Object?> _toList() {
    return <Object?>[processed, remaining];
  }

  Object encode() {
    return _toList();
  }

  static RunResult decode(Object result) {
    result as List<Object?>;
    return RunResult(
      processed: result[0]! as int,
      remaining: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RunResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(processed, other.processed) &&
        _deepEquals(remaining, other.remaining);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RunResult(processed: $processed, remaining: $remaining)';
  }
}

class OcrLineMessage {
  OcrLineMessage({
    required this.text,
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  });

  String text;

  int left;

  int top;

  int right;

  int bottom;

  List<Object?> _toList() {
    return <Object?>[text, left, top, right, bottom];
  }

  Object encode() {
    return _toList();
  }

  static OcrLineMessage decode(Object result) {
    result as List<Object?>;
    return OcrLineMessage(
      text: result[0]! as String,
      left: result[1]! as int,
      top: result[2]! as int,
      right: result[3]! as int,
      bottom: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OcrLineMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(text, other.text) &&
        _deepEquals(left, other.left) &&
        _deepEquals(top, other.top) &&
        _deepEquals(right, other.right) &&
        _deepEquals(bottom, other.bottom);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OcrLineMessage(text: $text, left: $left, top: $top, right: $right, bottom: $bottom)';
  }
}

class OcrBlockMessage {
  OcrBlockMessage({required this.lines});

  List<OcrLineMessage> lines;

  List<Object?> _toList() {
    return <Object?>[lines];
  }

  Object encode() {
    return _toList();
  }

  static OcrBlockMessage decode(Object result) {
    result as List<Object?>;
    return OcrBlockMessage(
      lines: (result[0]! as List<Object?>).cast<OcrLineMessage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OcrBlockMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(lines, other.lines);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OcrBlockMessage(lines: $lines)';
  }
}

class TokenBatch {
  TokenBatch({
    required this.inputIds,
    required this.attentionMask,
    required this.tokenTypeIds,
    required this.sequenceLength,
  });

  /// Row-major, batch size times [sequenceLength].
  Int64List inputIds;

  Int64List attentionMask;

  Int64List tokenTypeIds;

  int sequenceLength;

  List<Object?> _toList() {
    return <Object?>[inputIds, attentionMask, tokenTypeIds, sequenceLength];
  }

  Object encode() {
    return _toList();
  }

  static TokenBatch decode(Object result) {
    result as List<Object?>;
    return TokenBatch(
      inputIds: result[0]! as Int64List,
      attentionMask: result[1]! as Int64List,
      tokenTypeIds: result[2]! as Int64List,
      sequenceLength: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TokenBatch || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(inputIds, other.inputIds) &&
        _deepEquals(attentionMask, other.attentionMask) &&
        _deepEquals(tokenTypeIds, other.tokenTypeIds) &&
        _deepEquals(sequenceLength, other.sequenceLength);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TokenBatch(inputIds: $inputIds, attentionMask: $attentionMask, tokenTypeIds: $tokenTypeIds, sequenceLength: $sequenceLength)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is GalleryPermission) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is GalleryImage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is GalleryPage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is CopiedImage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is CopyFailure) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is CopyResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is CaptureStatus) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is InboxItem) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is SchedulePolicy) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is RunResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is OcrLineMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is OcrBlockMessage) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is TokenBatch) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : GalleryPermission.values[value];
      case 130:
        return GalleryImage.decode(readValue(buffer)!);
      case 131:
        return GalleryPage.decode(readValue(buffer)!);
      case 132:
        return CopiedImage.decode(readValue(buffer)!);
      case 133:
        return CopyFailure.decode(readValue(buffer)!);
      case 134:
        return CopyResult.decode(readValue(buffer)!);
      case 135:
        return CaptureStatus.decode(readValue(buffer)!);
      case 136:
        return InboxItem.decode(readValue(buffer)!);
      case 137:
        return SchedulePolicy.decode(readValue(buffer)!);
      case 138:
        return RunResult.decode(readValue(buffer)!);
      case 139:
        return OcrLineMessage.decode(readValue(buffer)!);
      case 140:
        return OcrBlockMessage.decode(readValue(buffer)!);
      case 141:
        return TokenBatch.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class GalleryHostApi {
  /// Constructor for [GalleryHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  GalleryHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<GalleryPermission> permissionState() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.GalleryHostApi.permissionState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as GalleryPermission;
  }

  Future<GalleryPermission> requestPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.GalleryHostApi.requestPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as GalleryPermission;
  }

  Future<void> openAppSettings() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.GalleryHostApi.openAppSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Images newest taken first.
  Future<GalleryPage> listImages(int offset, int limit) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.GalleryHostApi.listImages$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[offset, limit],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as GalleryPage;
  }

  /// JPEG bytes no larger than [size] on the long edge.
  Future<Uint8List> thumbnail(String uri, int size) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.GalleryHostApi.thumbnail$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri, size],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Opens the system Photo Picker. Returns selected content URIs.
  Future<List<String>> pickWithSystemPicker(int maxItems) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.GalleryHostApi.pickWithSystemPicker$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[maxItems],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Streams each URI into `files/originals/` and reports file facts.
  Future<CopyResult> copyToAppStorage(List<String> uris) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.GalleryHostApi.copyToAppStorage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uris],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CopyResult;
  }

  /// Writes a thumbnail for an image already in app storage. Returns the
  /// relative path of the thumbnail.
  Future<String> createThumbnail(String relativeSourcePath, int maxEdge) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.GalleryHostApi.createThumbnail$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[relativeSourcePath, maxEdge],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }
}

class CaptureHostApi {
  /// Constructor for [CaptureHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CaptureHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CaptureStatus> status() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.CaptureHostApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CaptureStatus;
  }

  Future<void> openAccessibilitySettings() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.CaptureHostApi.openAccessibilitySettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Android 13+: asks the system to add the Memora tile.
  Future<bool> requestAddTile() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.CaptureHostApi.requestAddTile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> requestNotificationPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.CaptureHostApi.requestNotificationPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Moves inbox files into `originals/` and returns their facts. Items stay
  /// in the inbox until [confirmInbox] acknowledges them, so a capture
  /// survives a worker that is stopped halfway.
  Future<List<InboxItem>> drainInbox() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.CaptureHostApi.drainInbox$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<InboxItem>();
  }

  /// Drops inbox entries whose memories now exist. Anything left unconfirmed
  /// is offered again by the next [drainInbox].
  Future<void> confirmInbox(List<String> ids) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.CaptureHostApi.confirmInbox$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ids],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

class SchedulerHostApi {
  /// Constructor for [SchedulerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SchedulerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Replaces pending processing work to match [policy].
  Future<void> apply(SchedulePolicy policy) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.SchedulerHostApi.apply$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[policy],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Runs the queue now, ignoring the time window, for this batch only.
  Future<void> processNow(bool requiresUnmeteredNetwork) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.SchedulerHostApi.processNow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[requiresUnmeteredNetwork],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancelAll() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.SchedulerHostApi.cancelAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Called by Android workers on the headless engine.
abstract class BackgroundFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<int> ingestInbox();

  Future<RunResult> runQueue(int budgetMillis, bool processNow);

  Future<int> reindexEmbeddings(int budgetMillis);

  static void setUp(
    BackgroundFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.memora.BackgroundFlutterApi.ingestInbox$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            final int output = await api.ingestInbox();
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.memora.BackgroundFlutterApi.runQueue$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_budgetMillis = args[0]! as int;
          final bool arg_processNow = args[1]! as bool;
          try {
            final RunResult output = await api.runQueue(
              arg_budgetMillis,
              arg_processNow,
            );
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.memora.BackgroundFlutterApi.reindexEmbeddings$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_budgetMillis = args[0]! as int;
          try {
            final int output = await api.reindexEmbeddings(arg_budgetMillis);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

/// Called by the headless Dart entrypoint once it can receive calls.
class BackgroundHostApi {
  /// Constructor for [BackgroundHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BackgroundHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> backgroundReady() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.BackgroundHostApi.backgroundReady$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// The entrypoint could not build its services. Ends the worker right away
  /// instead of waiting for the readiness timeout.
  Future<void> backgroundFailed(String message) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.BackgroundHostApi.backgroundFailed$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[message],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

class SecretHostApi {
  /// Constructor for [SecretHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SecretHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String?> read(String key) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.SecretHostApi.read$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<void> write(String key, String value) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.SecretHostApi.write$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> delete(String key) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.SecretHostApi.delete$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<String>> keys() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.SecretHostApi.keys$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }
}

class OcrHostApi {
  /// Constructor for [OcrHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  OcrHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<OcrBlockMessage>> recognize(String absolutePath) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.OcrHostApi.recognize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[absolutePath],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<OcrBlockMessage>();
  }
}

class EmbeddingHostApi {
  /// Constructor for [EmbeddingHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  EmbeddingHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> load(String absoluteModelPath) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.EmbeddingHostApi.load$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[absoluteModelPath],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> isLoaded() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.EmbeddingHostApi.isLoaded$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Returns batch size times dimensions values, row-major, L2-normalized.
  /// Pigeon has no Float32List, so values cross the bridge as doubles.
  Future<Float64List> run(TokenBatch batch) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.EmbeddingHostApi.run$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[batch],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Float64List;
  }
}

class FilesHostApi {
  /// Constructor for [FilesHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FilesHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Absolute path of the app files directory.
  Future<String> filesDir() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.FilesHostApi.filesDir$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  /// Opens the system "save as" dialog and copies [absoluteSourcePath] to the
  /// chosen location. Returns false if the user cancelled.
  Future<bool> saveToUserLocation(
    String absoluteSourcePath,
    String suggestedName,
    String mimeType,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.memora.FilesHostApi.saveToUserLocation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[absoluteSourcePath, suggestedName, mimeType],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
