// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.gameon223.memora.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class GalleryPermission(val raw: Int) {
  /** Full access to images. */
  GRANTED(0),
  /** Android 14+ partial access to images the user picked. */
  PARTIAL(1),
  DENIED(2),
  /** Denied and Android will no longer show the prompt. */
  PERMANENTLY_DENIED(3);

  companion object {
    fun ofRaw(raw: Int): GalleryPermission? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GalleryImage (
  /** `content://` URI. */
  val uri: String,
  val takenAtMillis: Long,
  val width: Long,
  val height: Long,
  val byteSize: Long,
  val mimeType: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GalleryImage {
      val uri = pigeonVar_list[0] as String
      val takenAtMillis = pigeonVar_list[1] as Long
      val width = pigeonVar_list[2] as Long
      val height = pigeonVar_list[3] as Long
      val byteSize = pigeonVar_list[4] as Long
      val mimeType = pigeonVar_list[5] as String
      return GalleryImage(uri, takenAtMillis, width, height, byteSize, mimeType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      takenAtMillis,
      width,
      height,
      byteSize,
      mimeType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GalleryImage
    return MessagesPigeonUtils.deepEquals(this.uri, other.uri) && MessagesPigeonUtils.deepEquals(this.takenAtMillis, other.takenAtMillis) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height) && MessagesPigeonUtils.deepEquals(this.byteSize, other.byteSize) && MessagesPigeonUtils.deepEquals(this.mimeType, other.mimeType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.takenAtMillis)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.byteSize)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mimeType)
    return result
  }
  override fun toString(): String {
    return "GalleryImage(uri=$uri, takenAtMillis=$takenAtMillis, width=$width, height=$height, byteSize=$byteSize, mimeType=$mimeType)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GalleryPage (
  val images: List<GalleryImage>,
  val hasMore: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GalleryPage {
      val images = pigeonVar_list[0] as List<GalleryImage>
      val hasMore = pigeonVar_list[1] as Boolean
      return GalleryPage(images, hasMore)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      images,
      hasMore,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GalleryPage
    return MessagesPigeonUtils.deepEquals(this.images, other.images) && MessagesPigeonUtils.deepEquals(this.hasMore, other.hasMore)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.images)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasMore)
    return result
  }
  override fun toString(): String {
    return "GalleryPage(images=$images, hasMore=$hasMore)"
  }
}

/**
 * A file copied into app storage.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CopiedImage (
  val sourceUri: String,
  /** Relative to the app files dir, for example `originals/<uuid>.png`. */
  val relativePath: String,
  val sha256: String,
  val mimeType: String,
  val width: Long,
  val height: Long,
  val byteSize: Long,
  val takenAtMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CopiedImage {
      val sourceUri = pigeonVar_list[0] as String
      val relativePath = pigeonVar_list[1] as String
      val sha256 = pigeonVar_list[2] as String
      val mimeType = pigeonVar_list[3] as String
      val width = pigeonVar_list[4] as Long
      val height = pigeonVar_list[5] as Long
      val byteSize = pigeonVar_list[6] as Long
      val takenAtMillis = pigeonVar_list[7] as Long
      return CopiedImage(sourceUri, relativePath, sha256, mimeType, width, height, byteSize, takenAtMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourceUri,
      relativePath,
      sha256,
      mimeType,
      width,
      height,
      byteSize,
      takenAtMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CopiedImage
    return MessagesPigeonUtils.deepEquals(this.sourceUri, other.sourceUri) && MessagesPigeonUtils.deepEquals(this.relativePath, other.relativePath) && MessagesPigeonUtils.deepEquals(this.sha256, other.sha256) && MessagesPigeonUtils.deepEquals(this.mimeType, other.mimeType) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height) && MessagesPigeonUtils.deepEquals(this.byteSize, other.byteSize) && MessagesPigeonUtils.deepEquals(this.takenAtMillis, other.takenAtMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourceUri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.relativePath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sha256)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mimeType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.byteSize)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.takenAtMillis)
    return result
  }
  override fun toString(): String {
    return "CopiedImage(sourceUri=$sourceUri, relativePath=$relativePath, sha256=$sha256, mimeType=$mimeType, width=$width, height=$height, byteSize=$byteSize, takenAtMillis=$takenAtMillis)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CopyFailure (
  val sourceUri: String,
  val message: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CopyFailure {
      val sourceUri = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      return CopyFailure(sourceUri, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourceUri,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CopyFailure
    return MessagesPigeonUtils.deepEquals(this.sourceUri, other.sourceUri) && MessagesPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourceUri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "CopyFailure(sourceUri=$sourceUri, message=$message)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CopyResult (
  val copied: List<CopiedImage>,
  val failed: List<CopyFailure>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CopyResult {
      val copied = pigeonVar_list[0] as List<CopiedImage>
      val failed = pigeonVar_list[1] as List<CopyFailure>
      return CopyResult(copied, failed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      copied,
      failed,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CopyResult
    return MessagesPigeonUtils.deepEquals(this.copied, other.copied) && MessagesPigeonUtils.deepEquals(this.failed, other.failed)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.copied)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.failed)
    return result
  }
  override fun toString(): String {
    return "CopyResult(copied=$copied, failed=$failed)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CaptureStatus (
  /** Android 11 or newer. */
  val accessibilitySupported: Boolean,
  val accessibilityEnabled: Boolean,
  /** Android 13+ can prompt to add the tile directly. */
  val canRequestTile: Boolean,
  val notificationsAllowed: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CaptureStatus {
      val accessibilitySupported = pigeonVar_list[0] as Boolean
      val accessibilityEnabled = pigeonVar_list[1] as Boolean
      val canRequestTile = pigeonVar_list[2] as Boolean
      val notificationsAllowed = pigeonVar_list[3] as Boolean
      return CaptureStatus(accessibilitySupported, accessibilityEnabled, canRequestTile, notificationsAllowed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accessibilitySupported,
      accessibilityEnabled,
      canRequestTile,
      notificationsAllowed,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CaptureStatus
    return MessagesPigeonUtils.deepEquals(this.accessibilitySupported, other.accessibilitySupported) && MessagesPigeonUtils.deepEquals(this.accessibilityEnabled, other.accessibilityEnabled) && MessagesPigeonUtils.deepEquals(this.canRequestTile, other.canRequestTile) && MessagesPigeonUtils.deepEquals(this.notificationsAllowed, other.notificationsAllowed)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accessibilitySupported)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accessibilityEnabled)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.canRequestTile)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.notificationsAllowed)
    return result
  }
  override fun toString(): String {
    return "CaptureStatus(accessibilitySupported=$accessibilitySupported, accessibilityEnabled=$accessibilityEnabled, canRequestTile=$canRequestTile, notificationsAllowed=$notificationsAllowed)"
  }
}

/**
 * A capture or share waiting in `files/inbox/`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InboxItem (
  /**
   * Inbox id, passed back to [CaptureHostApi.confirmInbox] once the memory
   * row exists.
   */
  val id: String,
  val relativePath: String,
  /** `tile` or `share`. */
  val source: String,
  val capturedAtMillis: Long,
  val sha256: String,
  val mimeType: String,
  val width: Long,
  val height: Long,
  val byteSize: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InboxItem {
      val id = pigeonVar_list[0] as String
      val relativePath = pigeonVar_list[1] as String
      val source = pigeonVar_list[2] as String
      val capturedAtMillis = pigeonVar_list[3] as Long
      val sha256 = pigeonVar_list[4] as String
      val mimeType = pigeonVar_list[5] as String
      val width = pigeonVar_list[6] as Long
      val height = pigeonVar_list[7] as Long
      val byteSize = pigeonVar_list[8] as Long
      return InboxItem(id, relativePath, source, capturedAtMillis, sha256, mimeType, width, height, byteSize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      relativePath,
      source,
      capturedAtMillis,
      sha256,
      mimeType,
      width,
      height,
      byteSize,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InboxItem
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.relativePath, other.relativePath) && MessagesPigeonUtils.deepEquals(this.source, other.source) && MessagesPigeonUtils.deepEquals(this.capturedAtMillis, other.capturedAtMillis) && MessagesPigeonUtils.deepEquals(this.sha256, other.sha256) && MessagesPigeonUtils.deepEquals(this.mimeType, other.mimeType) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height) && MessagesPigeonUtils.deepEquals(this.byteSize, other.byteSize)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.relativePath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.capturedAtMillis)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sha256)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mimeType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.byteSize)
    return result
  }
  override fun toString(): String {
    return "InboxItem(id=$id, relativePath=$relativePath, source=$source, capturedAtMillis=$capturedAtMillis, sha256=$sha256, mimeType=$mimeType, width=$width, height=$height, byteSize=$byteSize)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SchedulePolicy (
  val immediate: Boolean,
  val paused: Boolean,
  val windowStartMinutes: Long,
  val windowEndMinutes: Long,
  /** True when a selected capability sends data off the device. */
  val requiresUnmeteredNetwork: Boolean,
  /** False lets the scheduler cancel pending work. */
  val hasWork: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SchedulePolicy {
      val immediate = pigeonVar_list[0] as Boolean
      val paused = pigeonVar_list[1] as Boolean
      val windowStartMinutes = pigeonVar_list[2] as Long
      val windowEndMinutes = pigeonVar_list[3] as Long
      val requiresUnmeteredNetwork = pigeonVar_list[4] as Boolean
      val hasWork = pigeonVar_list[5] as Boolean
      return SchedulePolicy(immediate, paused, windowStartMinutes, windowEndMinutes, requiresUnmeteredNetwork, hasWork)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      immediate,
      paused,
      windowStartMinutes,
      windowEndMinutes,
      requiresUnmeteredNetwork,
      hasWork,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SchedulePolicy
    return MessagesPigeonUtils.deepEquals(this.immediate, other.immediate) && MessagesPigeonUtils.deepEquals(this.paused, other.paused) && MessagesPigeonUtils.deepEquals(this.windowStartMinutes, other.windowStartMinutes) && MessagesPigeonUtils.deepEquals(this.windowEndMinutes, other.windowEndMinutes) && MessagesPigeonUtils.deepEquals(this.requiresUnmeteredNetwork, other.requiresUnmeteredNetwork) && MessagesPigeonUtils.deepEquals(this.hasWork, other.hasWork)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.immediate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.paused)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.windowStartMinutes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.windowEndMinutes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requiresUnmeteredNetwork)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasWork)
    return result
  }
  override fun toString(): String {
    return "SchedulePolicy(immediate=$immediate, paused=$paused, windowStartMinutes=$windowStartMinutes, windowEndMinutes=$windowEndMinutes, requiresUnmeteredNetwork=$requiresUnmeteredNetwork, hasWork=$hasWork)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RunResult (
  val processed: Long,
  val remaining: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RunResult {
      val processed = pigeonVar_list[0] as Long
      val remaining = pigeonVar_list[1] as Boolean
      return RunResult(processed, remaining)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      processed,
      remaining,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RunResult
    return MessagesPigeonUtils.deepEquals(this.processed, other.processed) && MessagesPigeonUtils.deepEquals(this.remaining, other.remaining)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.processed)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.remaining)
    return result
  }
  override fun toString(): String {
    return "RunResult(processed=$processed, remaining=$remaining)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OcrLineMessage (
  val text: String,
  val left: Long,
  val top: Long,
  val right: Long,
  val bottom: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OcrLineMessage {
      val text = pigeonVar_list[0] as String
      val left = pigeonVar_list[1] as Long
      val top = pigeonVar_list[2] as Long
      val right = pigeonVar_list[3] as Long
      val bottom = pigeonVar_list[4] as Long
      return OcrLineMessage(text, left, top, right, bottom)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      left,
      top,
      right,
      bottom,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OcrLineMessage
    return MessagesPigeonUtils.deepEquals(this.text, other.text) && MessagesPigeonUtils.deepEquals(this.left, other.left) && MessagesPigeonUtils.deepEquals(this.top, other.top) && MessagesPigeonUtils.deepEquals(this.right, other.right) && MessagesPigeonUtils.deepEquals(this.bottom, other.bottom)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.text)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.left)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.top)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.right)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bottom)
    return result
  }
  override fun toString(): String {
    return "OcrLineMessage(text=$text, left=$left, top=$top, right=$right, bottom=$bottom)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OcrBlockMessage (
  val lines: List<OcrLineMessage>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OcrBlockMessage {
      val lines = pigeonVar_list[0] as List<OcrLineMessage>
      return OcrBlockMessage(lines)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lines,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OcrBlockMessage
    return MessagesPigeonUtils.deepEquals(this.lines, other.lines)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lines)
    return result
  }
  override fun toString(): String {
    return "OcrBlockMessage(lines=$lines)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TokenBatch (
  /** Row-major, batch size times [sequenceLength]. */
  val inputIds: LongArray,
  val attentionMask: LongArray,
  val tokenTypeIds: LongArray,
  val sequenceLength: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TokenBatch {
      val inputIds = pigeonVar_list[0] as LongArray
      val attentionMask = pigeonVar_list[1] as LongArray
      val tokenTypeIds = pigeonVar_list[2] as LongArray
      val sequenceLength = pigeonVar_list[3] as Long
      return TokenBatch(inputIds, attentionMask, tokenTypeIds, sequenceLength)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      inputIds,
      attentionMask,
      tokenTypeIds,
      sequenceLength,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TokenBatch
    return MessagesPigeonUtils.deepEquals(this.inputIds, other.inputIds) && MessagesPigeonUtils.deepEquals(this.attentionMask, other.attentionMask) && MessagesPigeonUtils.deepEquals(this.tokenTypeIds, other.tokenTypeIds) && MessagesPigeonUtils.deepEquals(this.sequenceLength, other.sequenceLength)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.inputIds)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attentionMask)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tokenTypeIds)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sequenceLength)
    return result
  }
  override fun toString(): String {
    return "TokenBatch(inputIds=${inputIds.contentToString()}, attentionMask=${attentionMask.contentToString()}, tokenTypeIds=${tokenTypeIds.contentToString()}, sequenceLength=$sequenceLength)"
  }
}

/**
 * What the device has to spare right now. Read before loading a model that
 * is measured in gigabytes.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceMemory (
  val totalBytes: Long,
  val availableBytes: Long,
  val lowRamDevice: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceMemory {
      val totalBytes = pigeonVar_list[0] as Long
      val availableBytes = pigeonVar_list[1] as Long
      val lowRamDevice = pigeonVar_list[2] as Boolean
      return DeviceMemory(totalBytes, availableBytes, lowRamDevice)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      totalBytes,
      availableBytes,
      lowRamDevice,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DeviceMemory
    return MessagesPigeonUtils.deepEquals(this.totalBytes, other.totalBytes) && MessagesPigeonUtils.deepEquals(this.availableBytes, other.availableBytes) && MessagesPigeonUtils.deepEquals(this.lowRamDevice, other.lowRamDevice)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.totalBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.availableBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.lowRamDevice)
    return result
  }
  override fun toString(): String {
    return "DeviceMemory(totalBytes=$totalBytes, availableBytes=$availableBytes, lowRamDevice=$lowRamDevice)"
  }
}

/**
 * A model file the user brought in, living under `files/models/imported/`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ImportedModel (
  /**
   * Relative to the app files dir, for example
   * `models/imported/gemma-3-1b-it-int4.task`.
   */
  val relativePath: String,
  val fileName: String,
  val byteSize: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ImportedModel {
      val relativePath = pigeonVar_list[0] as String
      val fileName = pigeonVar_list[1] as String
      val byteSize = pigeonVar_list[2] as Long
      return ImportedModel(relativePath, fileName, byteSize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      relativePath,
      fileName,
      byteSize,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ImportedModel
    return MessagesPigeonUtils.deepEquals(this.relativePath, other.relativePath) && MessagesPigeonUtils.deepEquals(this.fileName, other.fileName) && MessagesPigeonUtils.deepEquals(this.byteSize, other.byteSize)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.relativePath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fileName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.byteSize)
    return result
  }
  override fun toString(): String {
    return "ImportedModel(relativePath=$relativePath, fileName=$fileName, byteSize=$byteSize)"
  }
}

/**
 * One piece of a generation. [text] is the new text only, not the whole
 * answer so far. The last chunk for a request has [done] set, and carries
 * [error] when the generation failed partway.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LlmChunk (
  val requestId: Long,
  val text: String,
  val done: Boolean,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LlmChunk {
      val requestId = pigeonVar_list[0] as Long
      val text = pigeonVar_list[1] as String
      val done = pigeonVar_list[2] as Boolean
      val error = pigeonVar_list[3] as String?
      return LlmChunk(requestId, text, done, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      text,
      done,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LlmChunk
    return MessagesPigeonUtils.deepEquals(this.requestId, other.requestId) && MessagesPigeonUtils.deepEquals(this.text, other.text) && MessagesPigeonUtils.deepEquals(this.done, other.done) && MessagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requestId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.text)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.done)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "LlmChunk(requestId=$requestId, text=$text, done=$done, error=$error)"
  }
}

/**
 * How far the copy behind [ModelImportHostApi.pickModelFile] has got.
 *
 * [totalBytes] is the size the picked file claims, and zero when the source
 * would not say. A model is measured in gigabytes and the copy runs for
 * minutes, so this is what keeps the import from looking stuck.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ModelImportProgress (
  val copiedBytes: Long,
  val totalBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ModelImportProgress {
      val copiedBytes = pigeonVar_list[0] as Long
      val totalBytes = pigeonVar_list[1] as Long
      return ModelImportProgress(copiedBytes, totalBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      copiedBytes,
      totalBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ModelImportProgress
    return MessagesPigeonUtils.deepEquals(this.copiedBytes, other.copiedBytes) && MessagesPigeonUtils.deepEquals(this.totalBytes, other.totalBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.copiedBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.totalBytes)
    return result
  }
  override fun toString(): String {
    return "ModelImportProgress(copiedBytes=$copiedBytes, totalBytes=$totalBytes)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          GalleryPermission.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GalleryImage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GalleryPage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CopiedImage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CopyFailure.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CopyResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CaptureStatus.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InboxItem.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SchedulePolicy.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RunResult.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OcrLineMessage.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OcrBlockMessage.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TokenBatch.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceMemory.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ImportedModel.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LlmChunk.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ModelImportProgress.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GalleryPermission -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is GalleryImage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is GalleryPage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CopiedImage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is CopyFailure -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is CopyResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is CaptureStatus -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is InboxItem -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is SchedulePolicy -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is RunResult -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is OcrLineMessage -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is OcrBlockMessage -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is TokenBatch -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is DeviceMemory -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is ImportedModel -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is LlmChunk -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is ModelImportProgress -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface GalleryHostApi {
  fun permissionState(): GalleryPermission
  suspend fun requestPermission(): GalleryPermission
  fun openAppSettings()
  /** Images newest taken first. */
  suspend fun listImages(offset: Long, limit: Long): GalleryPage
  /** JPEG bytes no larger than [size] on the long edge. */
  suspend fun thumbnail(uri: String, size: Long): ByteArray
  /** Opens the system Photo Picker. Returns selected content URIs. */
  suspend fun pickWithSystemPicker(maxItems: Long): List<String>
  /** Streams each URI into `files/originals/` and reports file facts. */
  suspend fun copyToAppStorage(uris: List<String>): CopyResult
  /**
   * Writes a thumbnail for an image already in app storage. Returns the
   * relative path of the thumbnail.
   */
  suspend fun createThumbnail(relativeSourcePath: String, maxEdge: Long): String

  companion object {
    /** The codec used by GalleryHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `GalleryHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: GalleryHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.GalleryHostApi.permissionState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.permissionState())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.GalleryHostApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestPermission())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.GalleryHostApi.openAppSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openAppSettings()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.GalleryHostApi.listImages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val offsetArg = args[0] as Long
            val limitArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.listImages(offsetArg, limitArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.GalleryHostApi.thumbnail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val sizeArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.thumbnail(uriArg, sizeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.GalleryHostApi.pickWithSystemPicker$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val maxItemsArg = args[0] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.pickWithSystemPicker(maxItemsArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.GalleryHostApi.copyToAppStorage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urisArg = args[0] as List<String>
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.copyToAppStorage(urisArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.GalleryHostApi.createThumbnail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val relativeSourcePathArg = args[0] as String
            val maxEdgeArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.createThumbnail(relativeSourcePathArg, maxEdgeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CaptureHostApi {
  fun status(): CaptureStatus
  fun openAccessibilitySettings()
  /** Android 13+: asks the system to add the Memora tile. */
  suspend fun requestAddTile(): Boolean
  suspend fun requestNotificationPermission(): Boolean
  /**
   * Moves inbox files into `originals/` and returns their facts. Items stay
   * in the inbox until [confirmInbox] acknowledges them, so a capture
   * survives a worker that is stopped halfway.
   */
  suspend fun drainInbox(): List<InboxItem>
  /**
   * Drops inbox entries whose memories now exist. Anything left unconfirmed
   * is offered again by the next [drainInbox].
   */
  suspend fun confirmInbox(ids: List<String>)

  companion object {
    /** The codec used by CaptureHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `CaptureHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CaptureHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.CaptureHostApi.status$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.status())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.CaptureHostApi.openAccessibilitySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openAccessibilitySettings()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.CaptureHostApi.requestAddTile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestAddTile())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.CaptureHostApi.requestNotificationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestNotificationPermission())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.CaptureHostApi.drainInbox$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.drainInbox())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.CaptureHostApi.confirmInbox$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idsArg = args[0] as List<String>
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.confirmInbox(idsArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SchedulerHostApi {
  /** Replaces pending processing work to match [policy]. */
  fun apply(policy: SchedulePolicy)
  /** Runs the queue now, ignoring the time window, for this batch only. */
  fun processNow(requiresUnmeteredNetwork: Boolean)
  fun cancelAll()

  companion object {
    /** The codec used by SchedulerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `SchedulerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SchedulerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.SchedulerHostApi.apply$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val policyArg = args[0] as SchedulePolicy
            val wrapped: List<Any?> = try {
              api.apply(policyArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.SchedulerHostApi.processNow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requiresUnmeteredNetworkArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.processNow(requiresUnmeteredNetworkArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.SchedulerHostApi.cancelAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelAll()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Called by Android workers on the headless engine.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class BackgroundFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by BackgroundFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  suspend fun ingestInbox(): Long
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.memora.BackgroundFlutterApi.ingestInbox$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as Long
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun runQueue(budgetMillisArg: Long, processNowArg: Boolean): RunResult
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.memora.BackgroundFlutterApi.runQueue$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(budgetMillisArg, processNowArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as RunResult
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun reindexEmbeddings(budgetMillisArg: Long): Long
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.memora.BackgroundFlutterApi.reindexEmbeddings$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(budgetMillisArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as Long
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(MessagesPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
/**
 * Called by the headless Dart entrypoint once it can receive calls.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface BackgroundHostApi {
  fun backgroundReady()
  /**
   * The entrypoint could not build its services. Ends the worker right away
   * instead of waiting for the readiness timeout.
   */
  fun backgroundFailed(message: String)

  companion object {
    /** The codec used by BackgroundHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `BackgroundHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BackgroundHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.BackgroundHostApi.backgroundReady$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.backgroundReady()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.BackgroundHostApi.backgroundFailed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.backgroundFailed(messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SecretHostApi {
  fun read(key: String): String?
  fun write(key: String, value: String)
  fun delete(key: String)
  fun keys(): List<String>

  companion object {
    /** The codec used by SecretHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `SecretHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SecretHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.SecretHostApi.read$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.read(keyArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.SecretHostApi.write$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.write(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.SecretHostApi.delete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.delete(keyArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.SecretHostApi.keys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.keys())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface OcrHostApi {
  suspend fun recognize(absolutePath: String): List<OcrBlockMessage>

  companion object {
    /** The codec used by OcrHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `OcrHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OcrHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.OcrHostApi.recognize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val absolutePathArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.recognize(absolutePathArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface EmbeddingHostApi {
  suspend fun load(absoluteModelPath: String)
  fun isLoaded(): Boolean
  /**
   * Returns batch size times dimensions values, row-major, L2-normalized.
   * Pigeon has no Float32List, so values cross the bridge as doubles.
   */
  suspend fun run(batch: TokenBatch): DoubleArray

  companion object {
    /** The codec used by EmbeddingHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `EmbeddingHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: EmbeddingHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.EmbeddingHostApi.load$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val absoluteModelPathArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.load(absoluteModelPathArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.EmbeddingHostApi.isLoaded$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isLoaded())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.EmbeddingHostApi.run$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val batchArg = args[0] as TokenBatch
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.run(batchArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LlmHostApi {
  /**
   * Loads a model file from app storage. Safe to call again with the same
   * path and settings. Loading a different model unloads the previous one.
   */
  suspend fun load(relativeModelPath: String, vision: Boolean, maxTokens: Long)
  fun isLoaded(): Boolean
  fun loadedModelPath(): String?
  suspend fun unload()
  /**
   * Starts generation and returns a request id. Text arrives on the event
   * channel. Images are only accepted when the model was loaded with vision.
   */
  suspend fun startGeneration(prompt: String, images: List<ByteArray>, maxTokens: Long): Long
  fun cancelGeneration(requestId: Long)
  fun deviceMemory(): DeviceMemory

  companion object {
    /** The codec used by LlmHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `LlmHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LlmHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.LlmHostApi.load$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val relativeModelPathArg = args[0] as String
            val visionArg = args[1] as Boolean
            val maxTokensArg = args[2] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.load(relativeModelPathArg, visionArg, maxTokensArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.LlmHostApi.isLoaded$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isLoaded())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.LlmHostApi.loadedModelPath$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.loadedModelPath())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.LlmHostApi.unload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.unload()
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.LlmHostApi.startGeneration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptArg = args[0] as String
            val imagesArg = args[1] as List<ByteArray>
            val maxTokensArg = args[2] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.startGeneration(promptArg, imagesArg, maxTokensArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.LlmHostApi.cancelGeneration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelGeneration(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.LlmHostApi.deviceMemory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.deviceMemory())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class ChunksStreamHandler : MessagesPigeonEventChannelWrapper<LlmChunk> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: ChunksStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.memora.LlmEvents.chunks"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<LlmChunk>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<LlmChunk>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class ImportProgressStreamHandler : MessagesPigeonEventChannelWrapper<ModelImportProgress> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: ImportProgressStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.memora.LlmEvents.importProgress"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<ModelImportProgress>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<ModelImportProgress>) {}

override fun onCancel(p0: Any?) {}
}
      
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ModelImportHostApi {
  /**
   * Opens the system file picker for a model file and copies the chosen one
   * into app storage under models/. Returns null if the user cancels.
   */
  suspend fun pickModelFile(): ImportedModel?
  suspend fun deleteModel(relativePath: String)
  fun listModels(): List<ImportedModel>

  companion object {
    /** The codec used by ModelImportHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ModelImportHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ModelImportHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.ModelImportHostApi.pickModelFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.pickModelFile())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.ModelImportHostApi.deleteModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val relativePathArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.deleteModel(relativePathArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.ModelImportHostApi.listModels$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listModels())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LinksHostApi {
  /**
   * Opens [url] in whatever handles web links. Only http and https are
   * accepted: every link Memora opens is a page it names itself, and any
   * other scheme would be a way to start an arbitrary activity.
   *
   * Returns false when nothing on the phone can open it.
   */
  suspend fun openUrl(url: String): Boolean

  companion object {
    /** The codec used by LinksHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `LinksHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LinksHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.LinksHostApi.openUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.openUrl(urlArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FilesHostApi {
  /** Absolute path of the app files directory. */
  fun filesDir(): String
  /**
   * Opens the system "save as" dialog and copies [absoluteSourcePath] to the
   * chosen location. Returns false if the user cancelled.
   */
  suspend fun saveToUserLocation(absoluteSourcePath: String, suggestedName: String, mimeType: String): Boolean

  companion object {
    /** The codec used by FilesHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `FilesHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FilesHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.FilesHostApi.filesDir$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.filesDir())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.memora.FilesHostApi.saveToUserLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val absoluteSourcePathArg = args[0] as String
            val suggestedNameArg = args[1] as String
            val mimeTypeArg = args[2] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.saveToUserLocation(absoluteSourcePathArg, suggestedNameArg, mimeTypeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
